name: App CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Create application.properties
        run: |
          export SPRING_DATASOURCE_URL=${{ secrets.DEV_DB_URL }}
          export SPRING_DATASOURCE_USERNAME=${{ secrets.DEV_DB_USER }}
          export SPRING_DATASOURCE_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}
          echo "spring.datasource.driver-class-name=org.mariadb.jdbc.Driver" > src/main/resources/application-db.properties
          echo "spring.datasource.url=\${SPRING_DATASOURCE_URL:}" >> src/main/resources/application-db.properties
          echo "spring.datasource.username=\${SPRING_DATASOURCE_USERNAME:admin}" >> src/main/resources/application-db.properties
          echo "spring.datasource.password=\${SPRING_DATASOURCE_PASSWORD:}" >> src/main/resources/application-db.properties
          echo "spring.jpa.properties.hibernate.format_sql=true" >> src/main/resources/application-db.properties
          echo "spring.jpa.show-sql=true" >> src/main/resources/application-db.properties
          echo "spring.jpa.hibernate.ddl-auto=update" >> src/main/resources/application-db.properties
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/ainfras-target:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ainfras-target:latest